### ISSUE TITLE
please help

### ISSUE THREAD

**Issue by shane142** [HoShiMin/HookLib#13]
![image](https://user-images.githubusercontent.com/79443853/108681689-59ee7800-74e7-11eb-9591-e9fae5e7f749.png)

**Comment by HoShiMin** [comment]
Are you sure you cloned it with the Zydis submodule?
If yes, add paths to his includes and output libs to your project.

**Comment by shane142** [comment]
> Are you sure you cloned it with the Zydis submodule?
> If yes, add paths to his includes and output libs to your project.

I'm new to all this sorry, what do you mean by clone?

**Comment by shane142** [comment]
nvm I have fixed it some files didn't install

**Comment by uhpep** [comment]
> Are you sure you cloned it with the Zydis submodule? If yes, add paths to his includes and output libs to your project.

How can i add Hooklib and Zydis submodules? can you help me?

**Comment by HoShiMin** [comment]
@uhpep, use this:
```
git clone --recurse-submodules -j8 https://github.com/HoShiMin/HookLib
```
