### ISSUE TITLE
windows 10 1809 page_fault_in_nonpaged_area

### ISSUE THREAD

**Issue by YangKi1902** [HoShiMin/HookLib#2]
hello, this library is very useful, thank you for that. Today im try to test with windows 10 1809(x64) and got page_fault_in_nonpaged_area bugcheck error, anyways to fix it? sorry i just begining in  kernel development.

**Comment by HoShiMin** [comment]
What exactly are you doing to get this BSOD?

**Comment by YangKi1902** [comment]
RtlInitUnicodeString(&SymbolName, L"NtMapViewOfSection");
Target = MmGetSystemRoutineAddress(&SymbolName);
SetHook(NtMapViewOfSectionTarget, NtMapViewOfSection_Hook, &OriginalNtMapViewOfSection);// BSOD page_fault_in_nonpaged_area 
in my NtMapViewOfSection_Hook function i just simply return OriginalNtMapViewOfSection(...)
it's working good with all 32bit/64bit w7,w8,w8.1 and windows 10 32 bit, only except windows 10 17763 64bit.

**Comment by HoShiMin** [comment]
Hm, well, I'll check it, thanks for reporting

**Comment by HoShiMin** [comment]
Fixed
