### ISSUE TITLE
Странный баг

### ISSUE THREAD

**Issue by den7ba** [HoShiMin/HookLib#21]
Заметил странное поведение функции hook. Использую следующим образом в контексте обработки IRP:
OrigZwTerminateProcess = hook(ZwTerminateProcess, HookedZwTerminateProcess);
По какой-то причине может не работать и возвращает 0 и не хукает функцию. После перезагрузки пк(не пересобирая драйвер) начинает нормально работать. Есть какие либо идеи?

**Comment by den7ba** [comment]
После unhook не хочет хукать ту же функцию. Иногда не работает даже после рестарта пк. Магия? Или ZwTerminateProcess стоит получать динамически

**Comment by HoShiMin** [comment]
Может не работать, если в начале оригинальной функции есть инструкции, которые не удалось релоцировать в выделенный буфер из-за того, что буфер выделился дальше двух гигабайт от оригинальной функции. В ядре мы не можем попросить систему выделить память в произвольном месте, поэтому может оказаться, что какой-нибудь относительный джамп, который стоит в начале функции, невозможно переместить так далеко (иначе в нём переполнится оффсет и джамп начнёт прыгать в космос).
Предположу, что перехватываемый адрес смотрит не на оригинальную функцию, а на джамп на неё в таблице импорта драйвера. Можно попробовать её получить через MmGetSystemRoutineAddress и проверить. И если не поможет - надо сдампить начало оригинальной функции.

**Comment by den7ba** [comment]
Я уверен что функция оригинальная, ибо читаются начальные байты (48 8B C4 FA 48...). Ретурн происходит тут 
https://github.com/HoShiMin/HookLib/blob/master/HookLib/HookLib/HookLib.c#L1717 
Пример аргументов: relocatable(32, 114332963847632)

**Comment by HoShiMin** [comment]
@den7ba, а точно возврат там, где ты показал? Можешь показать в отладчике, какую инструкцию он попытался релоцировать?

**Comment by den7ba** [comment]
![image](https://user-images.githubusercontent.com/55707138/222920850-5e6d0310-79e1-48c3-a444-1a32ba6951e7.png)
 Точно там. Насчет отладчика, я без него. Наверное нужно посмотреть что вообще читает эта функция, ибо сама функция хукается иногда без проблем и работает. Какую переменную проверить чтоб глянуть инструкцию?

**Comment by den7ba** [comment]
![image](https://user-images.githubusercontent.com/55707138/222921480-1c90e11c-5bf8-4276-90bc-1c20ba11c342.png)
 По идее это первый байт функции?

**Comment by HoShiMin** [comment]
@den7ba, а сдампи первые 50 байт функции. Там сразу будет понятно, где что не так.

**Comment by den7ba** [comment]
![image](https://user-images.githubusercontent.com/55707138/222922765-e0542422-10dd-4597-b749-de184d4896a1.png)

**Comment by den7ba** [comment]
![image](https://user-images.githubusercontent.com/55707138/222924795-dadca2e2-e7e6-4202-8940-87f4cc589dfb.png)
Да, это была не первая инструкция..

**Comment by HoShiMin** [comment]
@den7ba, на x64 джампы требуют 14 байт. Он не сумел из-за этого lea:
![image](https://user-images.githubusercontent.com/3404752/222929803-f8990f1c-0a46-4868-9194-c85a21758bab.png)

Все Zw-функции через эти маленькие стабы прыгают на Nt-реализацию, поэтому всегда перехватывай именно Nt-варианты. NtTerminateProcess не экспортируется, но ты можешь найти её по сигнатурам или по символам.

**Comment by den7ba** [comment]
К сожалению через Nt идут и пользовательские вызовы( ладно, это не большая проблема. Я правильно понимаю, иногда функция хукается удачно из-за разного офсета до KiServiceLinkage?

**Comment by den7ba** [comment]
Дампы до успешного хука и после:
![image](https://user-images.githubusercontent.com/55707138/222951511-2521bba4-7409-4a3a-8fbb-cb19fb5a5281.png)
К слову, они не отличаются от дампа неудачного, который я скидывал выше

**Comment by HoShiMin** [comment]
> Я правильно понимаю, иногда функция хукается удачно из-за разного офсета до KiServiceLinkage?

Не совсем: в lea прописан оффсет относительно следующий инструкции. Когда мы переносим этот lea в выделенный буфер, может оказаться, что расстояние между новым местом lea и местом, куда оффсет смотрел раньше, настолько велико, что новый оффсет не влезает в 4 байта. В этом случае переместить инструкцию нельзя.  
Успешно или неуспешно - зависит от того, насколько далеко выделится буфер, куда мы кладём оригинальное начало функции. Если выделяется в пределах двух гигабайт вверх или вниз - то мы можем релоцировать такие инструкции. Если выделяется дальше - то не можем и фэйлимся.  
  
В твоём же случае, если тебе надо перехватить только вызовы от системы, то в Nt-хуке ты можешь проверять PreviousMode у потока, попавшего в хук, вызвав [ExGetPreviousMode](https://learn.microsoft.com/en-us/windows-hardware/drivers/ddi/wdm/nf-wdm-exgetpreviousmode). Если он равен UserMode, то вызов пришёл из юзермода, если KernelMode, то вызвали через Zw-сервис из ядра.

**Comment by den7ba** [comment]
Точно, я и забыл про предыдущий режим. Спасибо, проблема выяснена.
